{
 "title": "kubeready dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Global CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(1-rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"}) / sum(machine_cpu_cores)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\"}) / sum(machine_cpu_cores)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Cluster Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes)",
     "legendFormat": "Memory Usage in %"
    }
   ]
  },
  {
   "title": "# of Running Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "# of Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (node) (kube_node_info))"
    }
   ]
  },
  {
   "title": "Global RAM Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes)",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"}) / sum(machine_memory_bytes)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\"}) / sum(machine_memory_bytes)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "CPU Saturation (Load1 / CPU)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  instance:node_load1_per_cpu:ratio{job=\"node-exporter\", cluster=\"\"}\n  / scalar(count(instance:node_load1_per_cpu:ratio{job=\"node-exporter\", cluster=\"\"}))\n)  != 0\n"
    }
   ]
  },
  {
   "title": "# of Deployments",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kube_deployment_labels)", "legendFormat": "Deployments" }
   ]
  },
  {
   "title": "# of Namespaces",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_namespace_created)" }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(1-rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval]))",
       "legendFormat": "CPU Usage in %"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true
  },
  {
   "title": "Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kubernetes Pods QoS classes",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 18, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_qos_class) by (qos_class)",
       "legendFormat": "{{ qos_class }} pods"
      },
      { "expr": "sum(kube_pod_info)", "legendFormat": "Total pods" }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Global Network Utilization by Device",
     "type": "timeseries",
     "description": "Dropped noisy virtual devices for readability.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_bytes_total{device!~\"lxc.*|veth.*\"}[$__rate_interval])) by (device)",
       "legendFormat": "Recieved: {{device}}"
      },
      {
       "expr": "- sum(rate(node_network_transmit_bytes_total{device!~\"lxc.*|veth.*\"}[$__rate_interval]))  by (device)",
       "legendFormat": "Transmitted: {{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk I/O",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total{job=\"node-exporter\", instance=\"192.168.49.2:9100\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\"}[$__rate_interval])",
       "legendFormat": "vda read"
      },
      {
       "expr": "rate(node_disk_written_bytes_total{job=\"node-exporter\", instance=\"192.168.49.2:9100\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\"}[$__rate_interval])",
       "legendFormat": "vda io time"
      },
      {
       "expr": "rate(node_disk_io_time_seconds_total{job=\"node-exporter\", instance=\"192.168.49.2:9100\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\"}[$__rate_interval])",
       "legendFormat": "vda written"
      }
     ]
    }
   ]
  }
 ]
}